CREATE TYPE comment_category AS ENUM ('expression', 'release', 'rejoice', 'embrace')

CREATE TABLE hello_comment (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  nickname TEXT NOT NULL,
  user_location TEXT,
  date_posted TIMESTAMPTZ DEFAULT now() NOT NULL,
  content TEXT NOT NULL,
  category comment_category NOT NULL
);